name: admin-santiago-marulanda
recipe: drupal9
config:
  webroot: web
  php: '8.1'
  xdebug: true
services:
  appserver:
    build:
      - "vendor/bin/phpcs --config-set installed_paths /app/vendor/drupal/coder/coder_sniffer"
  database:
    type: mariadb
    portforward: true
tooling:
  phpcs:
    service: appserver
    cmd: "/app/vendor/bin/phpcs --standard=Drupal,DrupalPractice --extensions=php,module,inc,install,test,profile,theme,css,info,txt,md,yml"
    options:
      description: Run phpcs for given folder or file.
  phpcbf:
    service: appserver
    cmd: "/app/vendor/bin/phpcbf --standard=Drupal,DrupalPractice --extensions=php,module,inc,install,test,profile,theme,css,info,txt,md,yml"
    options:
      description: Run phpcs for given folder or file.

