name: Deployment Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Drupal core
        uses: actions/checkout@v2
        with:
          fetch-dept: 0

      - name: Setup PHP, Composer and Extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: xml, mbstring

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Drupal core dependencies
        run: |
            composer --no-interaction --no-progress --prefer-dist --optimize-autoloader install

      - name: Install Coder module
        run: |
          composer --dev --no-interaction --no-progress require \
            drupal/coder:8.3.13

      - name: Check coding standars
        run: |
          ./vendor/bin/phpcs --config-set installed_paths vendor/drupal/coder/coder_sniffer
          ./vendor/bin/phpcs --standard=Drupal,DrupalPractice --extensions=php,module,install,js ./web/modules/custom/*
